- hosts: all-hosts
  var:
    file_name: test
  tasks:
    
    - name: retrieve the data of {{file_name}}
      stat:
        path: "/tmp/{{file_name}}"
      register: file

    - debug: 
        msg: "the file exists"
      when: file.stat.exists == true